### ISSUE TITLE
backspace does not work

### ISSUE THREAD

**Issue by luxferresum** [pelzlpj/orpie#17]
I'm running on nixos and use the packaged version. However when I enter some numbers, *dont* press <Enter> to put them on the stack and then press <Backspace> nothing happens. However on the left in the help it says backspace is, well, backspace.

So pressing backspace in this situation is not doing anything:
![image](https://user-images.githubusercontent.com/1208273/60528846-ac1ccd00-9cf5-11e9-81fb-0aa03f508eb4.png)

**Comment by pelzlpj** [comment]
Backspace unfortunately has some terminal portability issues. As a
workaround, it is likely that ^H does what you want.

Paul

**Comment by pelzlpj** [comment]
In d5acae391e7d45dc347c78ff344450296a265e21 the default key bindings have been updated to map ASCII DEL to `edit_backspace`, which will likely address your issue.
