### ISSUE TITLE
create OPAM package

### ISSUE THREAD

**Issue by pelzlpj** [pelzlpj/orpie#5]

**Comment by pelzlpj** [comment]
Pending integration of https://github.com/ocaml/opam-repository/pull/12528 .

**Comment by mblakele** [comment]
I wanted to test this before it's in opam officially, but I'm new to opam. This process seems to work:

```bash
brew install opam &&
opam repo add orpie 'https://github.com/pelzlpj/opam-repository.git#opam-publish-orpie.1.6.0' &&
opam install orpie
```

**caveat:** I lose `calc_state` whenever I switch between my old, homebrew-install orpie 1.5.2 and the new opam orpie 1.6.0. That isn't important to me, but I thought I'd mention it.

**Comment by pelzlpj** [comment]
The caveat is not surprising, and is probably due to using different OCaml compilers. If memory serves, the state file is using built-in OCaml object serialization, which is not a stable format.

Anyway: Orpie went live on OPAM earlier today, so I'm closing this out.
