### ISSUE TITLE
orpie build fails with parallel make

### ISSUE THREAD

**Issue by jared-wallace** [pelzlpj/orpie#9]
When building with parallel make (make %{?_smp_mlags}) orpie fails with the following:

ocamlopt.opt -c -I ./curses -thread curses/curses.ml
File "curses_keys.ml", line 35, characters 45-75:
Error: Unbound module Curses_assist
Makefile:285: recipe for target 'curses_keys.cmx' failed
make: *** [curses_keys.cmx] Error 2
make: *** Waiting for unfinished jobs....
In file included from ml_curses.c:176:0:
functions.c: In function ‘mlcurses_getsyx’:
functions.c:295:10: warning: ‘x’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 BEG0 int x,y; getsyx(y,x); r_int_int(x,y); END
          ^
functions.c:295:12: warning: ‘y’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 BEG0 int x,y; getsyx(y,x); r_int_int(x,y); END
            ^
rm txtin_parser.mli txtin_lexer.ml
error: Bad exit status from /var/tmp/rpm-tmp.qCYiMy (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.qCYiMy (%build)

**Comment by pelzlpj** [comment]
Fixed in 1a2d225218213d850bdcd40ed87449c176690139.
